### ISSUE TITLE
Doesn't run, can't find keywords.txt

### ISSUE THREAD

**Issue by rversteegen** [GDQuest/emacs-gdscript-mode#28]
Commit 1717837d344d

- [x] Bug report.
- [ ] Feature request.

Myself and another person couldn't get this mode to load.
`(require 'gdscript-mode)`
produces the errors
```
Eager macro-expansion failure: (file-missing "Opening input file" "No such file or directory" "/mnt/common/docs2/keywords.txt")
let: Opening input file: No such file or directory, /mnt/common/docs2/keywords.txt
```
(The repo is cloned at `/mnt/common/docs2/elisp-local/emacs-gdscript-mode/`, and that path is in `load-path`)

Looking at the code it's obvious what the problem is. The function `gdscript--get-file-content-as-string` contains the line of code `(setq this-directory (file-name-directory "gdscript-mode.el"))`
This is wrong, `this-directory` is always `nil`.

**Comment by trcm** [comment]
+1 I also get this error when following the install instructions

**Comment by NathanLovato** [comment]
Any idea how to make it work everywhere? It works well here, that function is the one that expands the full path from a file name. I had also an or clause with buffer-file-name before but this gave me errors.

**Comment by rversteegen** [comment]
No, it doesn't...
> (file-name-directory FILENAME)
> 
> Return the directory component in file name FILENAME.

I found  http://ergoemacs.org/emacs/elisp_relative_path.html and tried
`      (setq this-directory (file-name-directory (or load-file-name buffer-file-name)))`
and it works for me.

**Comment by NathanLovato** [comment]
Yes, my bad. The line above seems to work. By the way, PRs are welcome when you find a way to fix a bug or improve a feature! I'll push the fix now.

**Comment by rversteegen** [comment]
Thanks, keep up the good work!

**Comment by NathanLovato** [comment]
Thanks for the report!
