### ISSUE TITLE
Add Keywords "and" and "or" to keywords.txt

### ISSUE THREAD

**Issue by SirRamEsq** [GDQuest/emacs-gdscript-mode#31]
## Feature request ##

After setting up this mode in emacs, I added the keywords "and" and "or" as it helps me to see them highlighted. I think it would be best to include these keywords in the "keywords.txt" file by default.

I'm not sure if this is an oversight or an intentional design decision, but I had wanted to point it out.

Feel free to close this if not relevant or if it goes against the design.

**Comment by NathanLovato** [comment]
Sure, thanks! You can tell us every language keyword that's missing and we'll add it.

**Comment by NathanLovato** [comment]
I actually pulled the keywords list from another project that was also incomplete. I added some but there might be others that are missing. And I'm not sure there's an easy and reliable place to parse in the source code to get them, unlike e.g. built-in types
