### ISSUE TITLE
Add a command to format the region with gdformat

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/emacs-gdscript-mode#38]
We can format the entire buffer, but not the selected region. I'm currently working on a 3rd party framework where I'd like to format some lines and not mess with the entire file, that's huge, causing a hang on save.

**Comment by NathanLovato** [comment]
@Scony is there a way to pass code to format from standard input to gdformat? Currently, it seems not. Without that, I think we can't add this feature.

Otherwise, here's how we can narrow the buffer to the region and send some code:

```elisp
(defun gdscript-format-region (beg end)
  "Run 'gdformat' on the lines within BEG and END.

WARNING: this may throw an error if the region contains a syntax error in
isolation, as the command first narrows the buffer down to the region."
  (interactive "rP")
  (save-restriction
    (narrow-to-region beg end)
    (gdscript-format-buffer)))
```

**Comment by Scony** [comment]
@NathanLovato yes:
```
$ echo 'tool' | gdformat -
tool
```

**Comment by NathanLovato** [comment]
Ah I had forgotten the -, thanks

**Comment by rafauke** [comment]
@NathanLovato have you considered https://github.com/purcell/reformatter.el for this?

**Comment by NathanLovato** [comment]
I briefly checked this, it's looking nice, but gotta see if it'll work for gdformat, as it has a special syntax to format from standard input, i.e. `echo some text | gdformat -`
