### ISSUE TITLE
Can start lsp

### ISSUE THREAD

**Issue by otavioschwanck** [GDQuest/emacs-gdscript-mode#64]
when i open a project (using doom) emacs, i got:
![image](https://user-images.githubusercontent.com/9551316/83416412-01c29380-a3f7-11ea-84be-b815ff860189.png)

How can i fix it ?

**Comment by NathanLovato** [comment]
You must use Godot 3.2.1+ for the language server to work with lsp-mode-gdscript. Older versions of the language server are not compatible.

Note it's not related to this package, lsp support is provided by the godot engine and lsp-mode.
