### ISSUE TITLE
Spacemacs installation instructions are incomplete

### ISSUE THREAD

**Issue by lolbinarycat** [GDQuest/emacs-gdscript-mode#68]
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
Following the instructions to install for spacemacs don't work.
Making it work requires you to rename the directory from `emacs-gdscript-mode` to `gdscript-mode`.

**What is the expected behavior?**
Following the instructions will result in a successful installation.

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

this format isn't working for this.
the solution is to add the extra step of renaming the directory to the spacemacs installation instructions.

## Feature request ##

**Describe the problem you're trying to solve.**

**Tell us which solutions you've explored, the solution you would pick, and why you think it would be the best for everyone.**

## Other ##

**Other information** 
I know I mangled the format, but there wasn't exactly a clear choice of what category this fell into, and I didn't really know what to do with it.

**Comment by NathanLovato** [comment]
It's outdated indeed. Now the package is on melpa, you don't need to download it manually. I'll update right away.
